data:
  tokenizer_path: "/path_to/gpt-clean-16000.json"
  train_path: "/path_to/babylm_10M_clean"
  eval_path: "/path_to/babylm_dev_clean"
  seq_length: 128
  eval_samples: 8192

model:
  type: "GPT2" # or "GPT2"
  name: "GPT2-705M"
  hidden_size: 1536
  intermediate_size: 3072 # train.py uses default = 4 * hidden_size
  n_layer: 24
  n_head: 16 # Change this if you're using GPT2
  resid_pdrop: 0.1
  attn_pdrop: 0.1
  embd_pdrop: 0.1

training:
  lr: 2.5e-4
  batch_size: 128
  num_epochs: 4
  gradient_accumulation_steps: 16
  warmup_steps: 300
  fp16: False

logging: 
  wandb: True
  project: "babylm-dev"
  output_dir: "./models/"

